# Generated by Django 5.2.4 on 2025-07-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'doctor-name',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hospital.doctor',),
        ),
    ]
